---
- name: My test playbook
  hosts: all
  become: true
  tasks:
    - name: Copying a file
      copy:
       src: /home/ansadmin/index.html
       dest: /home/ansadmin
       mode: 0600
       owner: akash  
