---
- name: My testbook
  hosts: all
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start Apache on RedHat
      service:
        name: htt--- #giving bug intentionally
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes


    - name: Install apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Apache on Debian
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
        mode: 0666
