---
- name: My Testbook
  hosts: all
  become: true

  tasks:
  - name: Stop httpd
    service:
      name: httpd
      state: stopped

  - name: Uninstall httpd
    yum:
     name: httpd
     state: removed    
